### ISSUE TITLE
Starter projects

### ISSUE THREAD

**Issue by jadjoubran** [chiraggude/awesome-laravel#101]
Thanks for this awesome (literally) repo!
I want to send a PR that adds a category for **Starter** projects, but I wanted to get your feedback first.
This is the package that I want to add https://github.com/jadjoubran/laravel5-angular-material-starter

**Comment by ricardobarantini** [comment]
I hope that category is included in the repo. :+1:

**Comment by chiraggude** [comment]
@jadjoubran Good idea! I have accepted #109

I will be renaming it to "Starter Projects" :)

Send a PR for your starter project as well.

**Comment by jadjoubran** [comment]
@chiraggude PR sent
