### ISSUE TITLE
New Rules for Packages

### ISSUE THREAD

**Issue by vinkla** [chiraggude/awesome-laravel#118]
New rules recently presented for this awesome list of awesome Laravel;
> I have been inundated with a large number of pull requests after Taylor Otwell retweeted a link to this repo. Starting now, I will be adding links to the "Popular Packages" section, only if the package has received more than 200 stars on Github. Because of this pre-requisite, a lot of helpful packages will fall through the cracks – but I think this fair to everyone involved. Apologies for the inconvenience.

Instead I think the points below will make it easier to choose which packages that should be added to this list or not. IMO, the downloads count and/or the number of stars you've on GitHub doesn't say anything about how good the package. For example, your package isn't awesome if you don't have any tests.

- Use [PSR-4](http://www.php-fig.org/psr/psr-4/) autoloader.
- Adhere to [PSR-2](http://www.php-fig.org/psr/psr-2/) as the coding style guide.
- Listed on [Packagist](https://packagist.org/).
- Has unit tests. Aim for at least 80% coverage in version 1.
- [DocBlock](http://www.phpdoc.org/docs/latest/references/phpdoc/index.html) all the things.
- Use Semantic Versioning to manage version numbers.
- Keep a [Changelog](http://keepachangelog.com/).
- Use [Travis-CI](https://travis-ci.org/) to automatically check coding standards and run tests.
- Have an extensive [README](https://github.com/thephpleague/skeleton/blob/master/README.md).
- [Exclude non-essential files in .gitattributes](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production).

Note that this is taken from http://thephpleague.com/

Started in #105.

**Comment by chiraggude** [comment]
This is a good starting point. Thanks for the help!

Now I lower the limit of Github stars required to get listed - Let's make it 100 stars.

**Comment by vinkla** [comment]
I think we should lower it even more, maybe below 50? Lets take [Laravel Fractal](https://github.com/spatie/laravel-fractal) which is built by @freekmurze. That package is awesome, it follows all the guidelines above. Currently the package (at the time of this comment) has 34 downloads and 42 stars on GitHub. Keeping 100 stars would mean that package wouldn't make it on this list. Even though it is well written, well documented and is built by trusted Laravel developers who makes a lot of good packages.

**Comment by arcanedev-maroc** [comment]
Create a `CONTRIBUTING.md` file and put these rules in it.

**Comment by vinkla** [comment]
@arcanedev-maroc That is a good idea :+1: We just need to discuss the rules first.

**Comment by chiraggude** [comment]
@arcanedev-maroc Yup! Will do this shortly.

**Comment by vinkla** [comment]
@chiraggude I've created a pull request in #119

**Comment by fishmad** [comment]
https://github.com/thekordy/ticketit
