### ISSUE TITLE
Add version rule

### ISSUE THREAD

**Issue by vinkla** [chiraggude/awesome-laravel#131]
IMO we should add a rule for what version the package, article or resource supports. All new pull requests should support at least `5.0` and maybe we should even go through the existing ones?

**Comment by chiraggude** [comment]
No point adding yet another restriction for new pull requests. I'll do it manually over the next few weeks. 

I also need to remove the dedicated "Laravel 5 sections" since 5.x has become the default in the entire community.

**Comment by GrahamCampbell** [comment]
I think we should. It's irresponsible to be publishing packages for versions older than 5.1.

**Comment by chiraggude** [comment]
Yeah, never hurts to promote best practices.

**Comment by chiraggude** [comment]
Done! fee5c0d
