### ISSUE TITLE
mention laravel/spark

### ISSUE THREAD

**Issue by sw-double** [chiraggude/awesome-laravel#142]
https://github.com/laravel/spark

**Comment by chiraggude** [comment]
Yup. Good time to add Spark since it is nearly ready to go public. 

Want to send me a PR under the "Starter Projects" section?

**Comment by pjmartorell** [comment]
[https://github.com/laravel/spark](https://github.com/laravel/spark) is no longer available

**Comment by drbyte** [comment]
According to posts on twitter it's been taken "private" _temporarily_ in preparation for a final move from beta to public release.
