### ISSUE TITLE
How to create pull request for adding new package?

### ISSUE THREAD

**Issue by ajmerainfo** [chiraggude/awesome-laravel#259]
I would like add two new package here.

Database Logger
https://github.com/klaravel/db-logger

Laravel 5.3 multi auth role and permission.
https://github.com/klaravel/ntrust

**Comment by GrahamCampbell** [comment]
They don't meet the minimum usage requirements.

**Comment by GrahamCampbell** [comment]
https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md

**Comment by ajmerainfo** [comment]
Got it @GrahamCampbell 

Thank you.
