### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HDVinnie** [chiraggude/awesome-laravel#299]
**laravel-achievements**
https://github.com/gstt/laravel-achievements

coming up on 100 stars so figured i would post here. Its a very nice package and meets all your requirements besides 100 stars.

**Comment by chiraggude** [comment]
Looks good! Send me a PR when you're ready :)

**Comment by HDVinnie** [comment]
https://github.com/gstt/laravel-achievements now meets requirements!
