### ISSUE TITLE
PR Template?

### ISSUE THREAD

**Issue by m1guelpf** [chiraggude/awesome-laravel#302]
How about an pr template?
Is a PR welcome for this?

**Comment by chiraggude** [comment]
Not many people create issues for this repo. Not sure if it will be helpful.

**Comment by m1guelpf** [comment]
@chiraggude Sorry, I meant PR Template

**Comment by chiraggude** [comment]
I barely get 1-2 PRs every week. Closing this for now but it's worth revisiting in the future. Cheers!
