### ISSUE TITLE
Add new package HackerEarth-API

### ISSUE THREAD

**Issue by ankitjain28may** [chiraggude/awesome-laravel#394]
Hi, I have created a package named HackerEarth-API which is using HackerEarth api to Compile and Run the code.

Check its code at [https://github.com/ankitjain28may/hackerearth-api](https://github.com/ankitjain28may/hackerearth-api)

Thanks

**Comment by ankitjain28may** [comment]
#396

**Comment by chiraggude** [comment]
Not enough stars: https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md
