### ISSUE TITLE
Why there are some repo without enough stars

### ISSUE THREAD

**Issue by goodjack** [chiraggude/awesome-laravel#416]
For example
- cybercog/laravel-ban
- keevitaja/linguist

**Comment by mr0bles** [comment]
Check the last commit of CONTRIBUTING.md

https://github.com/chiraggude/awesome-laravel/commit/466ca7ee1c17b7ce952d782fb43ed81d7990b3e5#diff-6a3371457528722a734f3c51d9238c13
