### ISSUE TITLE
README.md Broken Links

### ISSUE THREAD

**Issue by whthT** [chiraggude/awesome-laravel#478]
```bash
Issues :-(
> Links 
  1. [L266] 503 https://forgerecipes.com/  
  2. [L328] 403 https://www.udemy.com/courses/search/?q=laravel  
  3. [L463]  http://hechoenlaravel.com Connection reset by peer 
  4. [L469] 404 https://larachat.co/slack  
  5. [L506]  https://laravelcm.com/ Connection timed out - connect(2) for "laravelcm.com" port 443 
Wrote results to ab-results-README.md.json
Wrote filtered results to ab-results-README.md-filtered.json
Wrote markdown table results to ab-results-README.md-markdown-table.json
The command "awesome_bot README.md --allow-dupe --allow-redirect --allow-ssl" exited with 1.
```   

Travis gave me a print this way, and when I looked at the pull request page, I could see that the last page made a mistake at Travis for something similar to this output. I thought of removing these links, but I didn't find it logical to do so because I had links like Udemy and I wrote this post.

Travis : https://travis-ci.org/chiraggude/awesome-laravel/builds/488371874

**Comment by insign** [comment]
1 and 2 works for me. 3 there is a redirect for a farewell.

Em seg, 4 de fev de 2019 04:36, Musa Kurt <notifications@github.com
escreveu:

**Comment by whthT** [comment]
2. The reason for the error in the connection is that Udemy is designed to not respond to fetch requests. awesome_robot assigns fetch request to all links of the equestrian robot
