### ISSUE TITLE
add agorainvoicing

### ISSUE THREAD

**Issue by hbakhtiyor** [chiraggude/awesome-laravel#482]
agorainvoicing.com

**Comment by antonkomarev** [comment]
Why is it paid when everywhere written that it's free?

**Comment by hbakhtiyor** [comment]
where did you see it's paid?
https://github.com/ladybirdweb/agorainvoicing

**Comment by antonkomarev** [comment]
On website which you provided in first message.

**Comment by chiraggude** [comment]
Sorry, not enough stars: https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md
