### ISSUE TITLE
laraver.xyz should be removed from the list

### ISSUE THREAD

**Issue by LMCom** [chiraggude/awesome-laravel#498]
https://laraver.xyz/ has come to an end.

![grafik](https://user-images.githubusercontent.com/14162803/57854084-a459a580-77e7-11e9-8673-3d5b28486f3e.png)

**Comment by InstanceOfMichael** [comment]
What did it do?

**Comment by LMCom** [comment]
> What did it do?

It has come to an end.

**Comment by InstanceOfMichael** [comment]
What did it do before it came to an end?

**Comment by LMCom** [comment]
Good question. I found an old snapshot: https://web.archive.org/web/20190119192926/https://laraver.xyz/

**Comment by chiraggude** [comment]
Please submit a PR to remove this URL :)
