### ISSUE TITLE
Add laravel-commando

### ISSUE THREAD

**Issue by vkovic** [chiraggude/awesome-laravel#504]
Hi, I just created an interesting Laravel package that has some handy set of artisan commands like create or drop database, dump database or load from .sql dump, or to see which fields (and field types) are present in your models ...

Can you please add it, to the list. I think the most suitable section is `Tasks, Commands and Scheduling`. 

The link is: https://github.com/vkovic/laravel-commando

**Comment by chiraggude** [comment]
Sorry, not enough stars: https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md
