### ISSUE TITLE
Add Blade-X

### ISSUE THREAD

**Issue by AndrewCherabaev** [chiraggude/awesome-laravel#506]
Hi! In fact Spatie command has a lot of packages, and I fuond uinteresting one [Blade X](https://github.com/spatie/laravel-blade-x). It allows to use `<my-partial property="value" />` constructions instead of `@include('myPartial', ['property' => 'value'])`.

Could you please add it to `Utilities`?

**Comment by chiraggude** [comment]
Feel free to send a PR for https://github.com/spatie/laravel-blade-x
