### ISSUE TITLE
Add AdminLTE

### ISSUE THREAD

**Issue by AndrewCherabaev** [chiraggude/awesome-laravel#507]
[AdminLTE](https://github.com/jeroennoten/Laravel-AdminLTE) was quite useful for my work projects so it would be great if you add it to `Utilities`. Comparing to Laravel Nova it's free and more popular.

**Comment by aalaap** [comment]
This has nothing to do with Laravel itself.

**Comment by chiraggude** [comment]
Submit a PR under https://github.com/chiraggude/awesome-laravel#starter-projects
