### ISSUE TITLE
Arjun Yojan channel no more available.

### ISSUE THREAD

**Issue by naneri** [chiraggude/awesome-laravel#51]
Arjun Yojan video tutorials have been moved to channel Design Code Blade on youtube. Here is the laravel playlist - https://www.youtube.com/watch?v=eEGHLuzKMz4&list=PLl0rlrKS77Mr5T6k8ZPfvCcaJ8ctk1ChU

**Comment by chiraggude** [comment]
Thanks. Now fixed 17a0adbbdb99af3d87559a8fdb7c07918ab42aca
