### ISSUE TITLE
PHPstorm plugins

### ISSUE THREAD

**Issue by lloricode** [chiraggude/awesome-laravel#550]
Hi just want to include this

# Free
https://plugins.jetbrains.com/plugin/9525--env-files-support
https://plugins.jetbrains.com/plugin/10037-csv-plugin
https://plugins.jetbrains.com/plugin/9404-dingo-api-plugin
https://plugins.jetbrains.com/plugin/10233-discord-integration
https://plugins.jetbrains.com/plugin/9725-gitprefix/
https://plugins.jetbrains.com/plugin/7532-laravel
https://plugins.jetbrains.com/plugin/8006-material-theme-ui
https://plugins.jetbrains.com/plugin/7631-php-composer-json-support
https://plugins.jetbrains.com/plugin/4456-quick-notes

# Paid
Laravel Idea:
https://plugins.jetbrains.com/plugin/13441-laravel-idea
https://www.youtube.com/watch?v=Lzm_7ymlgAU

**Comment by chiraggude** [comment]
Thanks for the suggestion. For now, I don't feel adding links about IDEs is super helpful for Laravel users.
